CREATE DATABASE STATIONARYDB;
USE STATIONARYDB;
CREATE TABLE STAFF(regNo INT NOT NULL,Name VARCHAR(20) NULL,address VARCHAR(50) NULL,DOB DATE NULL,designation VARCHAR(10) NULL, JoinDate DATE NULL , PhoneNumber int NULL,userName VARCHAR(10) NULL,PRIMARY KEY (regNo),UNIQUE (regNo));
CREATE TABLE LOGIN(userId INT NOT NULL,UserName VARCHAR(10) NULL,Password VARCHAR(10) NULL,role VARCHAR(11) NULL,PRIMARY KEY (userId),UNIQUE (userId));

CREATE TABLE CATEGORY(category_Id int NOT NULL,Category VARCHAR(10) NULL,PRIMARY KEY (category_Id));
CREATE TABLE Items (ItemCode INT NOT NULL,ItemName VARCHAR(20) NULL,RecievedPrice DECIMAL(7,2) NULL,SellingPrice DECIMAL(7,2) NULL,Quanttity INT NULL, Total DECIMAL (7,2) NULL,Profit DECIMAL (7,2) NULL,Category VARCHAR(10) NULL,PRIMARY KEY(ItemCode));
CREATE TABLE Sales (SaleNo INT NOT NULL,date DATE , ItemCode INT NULL, ItemName VARCHAR(20) NULL,PRICE DECIMAL (7,2),Quantity INT,Total DECIMAL(7,2),PRIMARY KEY(SaleNo));
CREATE TABLE Bill(Orderno INT NOT NULL,DATE DATE, ITEMCODE INT,ITEMNMAE VARCHAR(20),PRICE DECIMAL(7,2),QUANTITY INT,TOTAL DECIMAL (7,2),PRIMARY KEY(Orderno));